### ISSUE TITLE
Target [App\Contracts\ZZZRepositoryInterface] is not instantiable while building [App\Http\Controllers\Admin\ZZZController]

### ISSUE THREAD

**Issue by shareef1989** [pratiksh404/adminetic#39]
Hi,

Thank you for this nice admin dashboard.

I followed the instructions mentioned [here](https://pratikdai404.gitbook.io/adminetic/example-walkthrough) but when I'm trying to browse the new model, I'm getting this error message:

Target [App\Contracts\ZZZRepositoryInterface] is not instantiable while building [App\Http\Controllers\Admin\ZZZController]

ZZZ is the model name

Do you have any idea about my mistake?

**Comment by pratiksh404** [comment]
> Hi,
> 
> Thank you for this nice admin dashboard.
> 
> I followed the instructions mentioned [here](https://pratikdai404.gitbook.io/adminetic/example-walkthrough) but when I'm trying to browse the new model, I'm getting this error message:
> 
> Target [App\Contracts\ZZZRepositoryInterface] is not instantiable while building [App\Http\Controllers\Admin\ZZZController]
> 
> ZZZ is the model name
> 
> Do you have any idea about my mistake?

In your service provider
