### ISSUE TITLE
Running command php artisan install:adminetic  produces error: Could not open input file: artisan

### ISSUE THREAD

**Issue by almakedon** [pratiksh404/adminetic#55]
Good day [pratiksh404](https://github.com/pratiksh404)

Running command 
php artisan install:adminetic  
produces error: Could not open input file: artisan

It requires artisan file but its not present in the folder.

I am trying to follow installation instruction , Am I missing something?

Thank you  for your time and help

**Comment by pratiksh404** [comment]
Maybe you're out of project root folder.
